"""Flask App configuration."""

# General Config
FLASK_DEBUG = False
SECRET_KEY = "SECRET_KEY"
OPENAI_API_KEY = "OPENAI_API_KEY"
SALESFORCE_ACCOUT_EMAIL = "SALESFORCE_ACCOUT_EMAIL"
SALESFORCE_PASSWORD = "SALESFORCE_PASSWORD"
SALESFORCE_CONSUMER_KEY = "SALESFORCE_CONSUMER_KEY"
SALESFORCE_CONSUMER_SECRET = "SALESFORCE_CONSUMER_SECRET"
GOOGLE_SEARCH_API_KEY = 'GOOGLE_SEARCH_API_KEY'
APP_ROOT_URL = "https://twilio-APP_ROOT_URL.com"
